name: Build image
on: [push]
jobs:

  smoke-test:
    runs-on: mrs-ci
    steps:

      - name: echo test
        run: echo test

      - name: nvidia-smi test
        run: nvidia-smi

      - name: pycuda test
        run: python -c "import pycuda.autoinit; print('yes')"

      - name: ls
        run: ls -l


  pytests:
    runs-on: mrs-ci
    steps:
      - uses: actions/checkout@v1
      - name: debug debug
        run: env && pwd && ls -lh
      - name: run pytest
        run: cd scientific_library && pytest