name: gputests
on: [push]
jobs:

  smoke-test:
    runs-on: self-hosted
    steps:

      - name: nvidia-smi test
        run: nvidia-smi

      - name: pycuda test
        run: python -c "import pycuda.autoinit; print('yes')"

      - name: pwd
        run: pwd


  gputest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: debug debug
        run: env && pwd && ls -lh
      - name: run pytest
        run:
          pip uninstall -y tvb-gdist &&
          pip install pylems &&
          cd scientific_library &&
          pytest /tvb/tests/library/simulator/rateml_test.py

#name: docker-based library testing
#on: [push]
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Build image
#        run: docker build -f scientific_library/Dockerfile -t tvb/lib-ci scientific_library
#      - name: Run tests
#        run: docker run --rm -v $PWD:/work -w /work/scientific_library tvb/lib-ci pytest -Wignore -n8