name: gputests
on: [push]
jobs:
  gputests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1

      - name: build Docker image
        run: cd scientific_library && docker build -t tvb/lib .

      - name: run library tests
        run: docker run --rm --gpus all -v $PWD:/tvb -w /tvb tvb/lib
