name: gputests
on: [push]
jobs:
  pytest:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v1

      - name: build Docker image
        run: cd scientific_library && docker build -t tvb/lib .

      - name: run library tests
        run: docker run --rm -it --gpus all -v $PWD:/tvb -w /tvb
